import{createHash}from'node:crypto';import{canonicalReportJson}from'../report/canonical-json.js';import{safePath}from'../report/redaction.js';import{normalizeSourceContent}from'../frontend/standard-json.js';import{SCAN_STAGES}from'./scan-stages.js';import{scanError}from'./errors.js';
export function sanitizeOrchestrationValue(value,seen=new Set()){if(value===undefined)return null;if(value===null||typeof value!=='object'||Buffer.isBuffer(value)||ArrayBuffer.isView(value))return value;if(seen.has(value))throw scanError('SCAN_STAGE_FAILED','Circular stage output cannot be serialized.');seen.add(value);const result=Array.isArray(value)?value.map(item=>sanitizeOrchestrationValue(item,seen)):Object.fromEntries(Object.entries(value).filter(([,item])=>item!==undefined).map(([key,item])=>[key,sanitizeOrchestrationValue(item,seen)]));seen.delete(value);return result;}
function digest(value){const text=canonicalReportJson(sanitizeOrchestrationValue(value));return`sha256:${createHash('sha256').update(text).digest('hex')}`;}
function sourceDigest(value){return`sha256:${createHash('sha256').update(Buffer.isBuffer(value)?value:Buffer.from(String(value),'utf8')).digest('hex')}`;}
function normalizedSourceDigest(value){return sourceDigest(Buffer.from(normalizeSourceContent(value),'utf8'));}
export function normalizedInput(input){if(!input||typeof input!=='object'||!input.sources||typeof input.sources!=='object'||!Object.keys(input.sources).length)throw scanError('SCAN_INPUT_INVALID','A non-empty project-relative Solidity source map is required.');const sources=Object.fromEntries(Object.entries(input.sources).sort(([a],[b])=>a<b?-1:a>b?1:0).map(([name,content])=>[safePath(name),content]));const domains=[...new Set(input.domains??[input.domain??input.policy?.domain??'arc-payments'])].sort();for(const domain of domains)if(!['arc-payments','arc-treasury','arc-private-credit'].includes(domain))throw scanError('SCAN_INPUT_INVALID',`Unsupported scan domain: ${domain}`);if((input.compilerVersion??'0.8.24')!=='0.8.24')throw scanError('SCAN_INPUT_INVALID','The supported orchestration profile requires exact solc 0.8.24.');return{...input,sources,domains,compilerVersion:'0.8.24'};}
export function inputIdentity(input){return digest({compilerVersion:input.compilerVersion,settings:input.settings??input.compilerSettings??{},domains:input.domains,sources:Object.fromEntries(Object.entries(input.sources).map(([name,content])=>[name,normalizedSourceDigest(content)])),policies:input.policies??input.policy??null,taxonomy:sourceDigest(typeof input.taxonomy==='string'?input.taxonomy:canonicalReportJson(input.taxonomy??{}))});}
export function createScanSession(input,options={}){const normalized=normalizedInput(input),abortController=new AbortController(),external=options.signal;if(external){if(external.aborted)abortController.abort(external.reason);else external.addEventListener('abort',()=>abortController.abort(external.reason),{once:true});}const telemetry=new Map(SCAN_STAGES.map(stageName=>[stageName,{stageName,status:'pending',startedAtMonotonic:null,endedAtMonotonic:null,durationMs:null,inputDigest:null,outputDigest:null,cacheHit:false,budget:null,budgetUsed:null,incompleteReasons:[],errorCode:null,progress:{}}]));const session={sessionId:inputIdentity(normalized),input:normalized,options,status:'pending',currentStage:null,stageOrder:[...SCAN_STAGES],stageCursor:0,results:new Map(),telemetry,events:[],incompleteReasons:new Set(),abortController,signal:abortController.signal,abortReason:null,startedAtMonotonic:null,deadlineMonotonic:null,metrics:{compilerInvocations:0}};return session;}
export{digest as orchestrationDigest};
