export const COMMON_CATALOG = Object.freeze({
  'title.disclosure': '{data} Exposed Through {surface}',
  'title.incomplete': 'Analysis Incomplete at {surface}',
  'title.observation': 'Public Calldata Observation',
  'summary.detected': '{data} reaches {surface} through a supported data-flow trace.',
  'summary.incomplete': 'Analysis reached {surface}, but the trace is incomplete and does not establish that risk is absent.',
  'summary.observation': '{data} is accepted through public calldata, which is observable on a public blockchain.',
  'explanation.detected': 'The value was classified as {data}, propagated through the recorded trace, and reached {surface} without an approved declassification.',
  'explanation.approved': 'The technical disclosure trace reaches {surface}; the active policy explicitly approves this occurrence.',
  'explanation.accepted': 'The technical risk trace reaches {surface}; a time-bounded accepted-risk record changes its disposition but does not remediate it.',
  'explanation.incomplete': 'The analyzer followed the classified source toward {surface}, then encountered an unsupported or unresolved boundary. Manual review is required.',
  'impact.arc-payments': 'This may expose or correlate payment parties, payroll or beneficiary data, amounts, or invoice and settlement references.',
  'impact.arc-treasury': 'This may reveal treasury operator, signer or approver relationships, limits, balances, destinations, or execution references.',
  'impact.arc-private-credit': 'This may reveal borrower or KYC data, loan terms, negotiated rates, collateral, or repayment and agreement references.',
  'remediation.title': 'Reduce the public financial-data surface',
  'remediation.event': 'Remove raw sensitive fields from event arguments.',
  'remediation.storage': 'Evaluate restricted or private storage and avoid exposing the same value through public accessors.',
  'remediation.getter': 'Replace unrestricted getters with role- or policy-controlled access where on-chain access is necessary.',
  'remediation.return': 'Remove sensitive fields from public or external return values.',
  'remediation.revert': 'Do not include sensitive data in revert strings or custom-error arguments.',
  'remediation.external': 'Minimize data before sending it across an external trust boundary and document the intended recipient.',
  'remediation.metadata': 'Do not place raw financial references in metadata or URIs; use an opaque off-chain reference where appropriate.',
  'remediation.calldata': 'Review the API so it does not accept unnecessary sensitive data through public calldata.',
  'remediation.policy': 'Use only a policy-approved commitment or wrapper with explicit scope and review.',
  'remediation.redact': 'Publish only the required aggregate or redacted value.',
  'remediation.label': 'Add an explicit policy label and review the intended disclosure.',
  'remediation.incomplete': 'Manually review the unresolved boundary before treating the analysis as complete.',
  'warning.plain-hash': 'Plain keccak256 or another unapproved hash does not establish privacy.',
  'warning.abi-encode': 'ABI encoding or bytes/string conversion does not hide a value.',
  'warning.private-getter': 'A private variable is not protected if a getter or event still exposes its value.',
  'warning.rename-event': 'Renaming an event parameter does not change what is observable on-chain.',
  'warning.rename-wrapper': 'Naming a function hash, encrypt, or private does not prove a protective transformation.',
  'warning.encoding': 'Base64 or hex encoding is representation, not privacy protection.',
  'warning.ui-only': 'Hiding or masking the value only in the UI does not remove on-chain disclosure.',
  'warning.closed-source': 'Keeping source code closed does not make public-chain data private.',
  'warning.accepted-risk': 'Accepted risk documents a decision; it is not a technical remediation.',
  'disposition.policy-approved': 'The technical occurrence is present but explicitly approved by the active policy, so it is not counted as an active violation. Re-evaluate it when the policy changes.',
  'disposition.accepted-risk': 'The technical risk remains present. Its owner, scope, and expiry are recorded; accepted risk is not remediation and must be re-evaluated after expiry.',
  'suppression.active': 'An explicit, valid suppression applies to this occurrence; the technical finding remains recorded.',
  'suppression.expired': 'The suppression is expired and is not active.',
  'suppression.invalid': 'The suppression record is invalid and is not active.',
  'incomplete.unresolved-call': 'Call resolution stopped at an unresolved target; manually review the runtime boundary.',
  'incomplete.low-level-call': 'A low-level call prevented complete target and value-flow resolution; manually review the boundary.',
  'incomplete.delegatecall': 'Delegatecall behavior could not be resolved safely; manually review target code and storage effects.',
  'incomplete.dynamic-function-pointer': 'A dynamic function pointer prevented complete call resolution; manually review its possible targets.',
  'incomplete.dynamic-storage-alias': 'A dynamic storage alias could not be resolved precisely; manually review the affected reads and writes.',
  'incomplete.inline-assembly': 'Inline assembly or Yul is outside the supported semantic model; manually review its data flow.',
  'incomplete.trace-budget': 'The analysis trace budget was reached; review the omitted flow before concluding the risk is absent.',
  'incomplete.unsupported-expression': 'An unsupported expression interrupted precise data-flow analysis; manually review that expression.',
  'incomplete.invalid-policy': 'The policy is invalid, so declassification and suppression decisions cannot be trusted until it is corrected.',
  'incomplete.unknown-metadata-builder': 'The metadata builder is unknown; manually review whether it publishes or transmits the sensitive value.',
  'incomplete.ambiguous-approval': 'The approval relationship is ambiguous; manually confirm approver, scope, and destination.',
  'incomplete.ambiguous-borrower': 'The borrower or customer relationship is ambiguous; manually confirm the financial context.',
  'incomplete.ambiguous-interest-rate': 'The interest-rate scope is ambiguous; manually determine whether it is borrower- or loan-specific.',
  'incomplete.ambiguous-collateral': 'The collateral relationship is ambiguous; manually confirm the asset, amount, reference, and manager context.',
  'incomplete.classification': 'Source or sink classification is incomplete; manually validate the financial-data role and disclosure surface.',
});

export const DATA_LABELS = Object.freeze({
  'customer-kyc-reference':'KYC Reference','employee-payroll':'Payroll Data','payment-amount':'Payment Amount',amount:'Financial Amount',payer:'Payer Identity',payee:'Payee Identity',beneficiary:'Beneficiary Data',supplier:'Supplier Data','treasury-operator':'Treasury Operator Data','invoice-reference':'Invoice Reference','settlement-reference':'Settlement Reference','loan-terms':'Loan Terms',collateral:'Collateral Data','interest-rate':'Negotiated Interest Rate',
});
export const SURFACE_LABELS = Object.freeze({ event:'Event Log','public-storage-getter':'Public Storage or Getter',return:'Public Function Return','revert-custom-error':'Revert or Custom Error','external-call':'External Boundary','metadata-uri':'Metadata or URI',calldata:'Public Calldata' });
export const EVIDENCE_LABELS = Object.freeze({ 'source-classification':'Sensitive source classification','source-location':'Sensitive source','trace-edge':'Data-flow step','callable-transition':'Callable transition','sink-classification':'Disclosure sink classification','sink-location':'Disclosure sink','declassification':'Policy declassification decision','accepted-risk':'Accepted-risk decision','incomplete-marker':'Analysis boundary' });
