import test from'node:test';import assert from'node:assert/strict';import{detectorResult,findings}from'./helpers.mjs';
test('duplicate representation of one detector occurrence groups',()=>{const r=detectorResult({token:'dup'});const run=findings([r,{...r,detectorResultId:'result-dup-copy'}]);assert.equal(run.findings.length,1);assert.equal(run.findings[0].occurrenceCount,1);assert.equal(run.findings[0].detectorResultIds.length,2);});
test('two real event occurrences do not merge',()=>assert.equal(findings([detectorResult({token:'e1'}),detectorResult({token:'e2'})]).findings.length,2));
test('different argument indexes do not merge',()=>assert.equal(findings([detectorResult({token:'a0',sinkCandidateId:'event-arg-0'}),detectorResult({token:'a1',sinkCandidateId:'event-arg-1'})]).findings.length,2));
test('storage and getter do not merge',()=>assert.equal(findings([detectorResult({token:'s',detectorId:'arc-payments.public-storage-disclosure',sinkClass:'public-storage-getter'}),detectorResult({token:'g',detectorId:'arc-payments.public-getter-disclosure',sinkClass:'public-storage-getter'})]).findings.length,2));
test('different callables do not merge',()=>assert.equal(findings([detectorResult({token:'c1',callableId:'call-1'}),detectorResult({token:'c2',callableId:'call-2'})]).findings.length,2));
test('different external targets do not merge through semantic sink identity',()=>assert.equal(findings([detectorResult({token:'x1',detectorId:'arc-payments.external-call-disclosure',sinkClass:'external-call',sinkCandidateId:'target-a'}),detectorResult({token:'x2',detectorId:'arc-payments.external-call-disclosure',sinkClass:'external-call',sinkCandidateId:'target-b'})]).findings.length,2));
test('event traces sharing one semantic event argument group into one finding',()=>{const first={...detectorResult({token:'event-trace-1'}),semanticSinkKey:'Out:event(uint256):0'},second={...detectorResult({token:'event-trace-2'}),semanticSinkKey:'Out:event(uint256):0'};assert.equal(findings([first,second]).findings.length,1);});
test('different semantic event arguments remain separate findings',()=>{const first={...detectorResult({token:'event-arg-key-0'}),semanticSinkKey:'Out:event(uint256,uint256):0'},second={...detectorResult({token:'event-arg-key-1'}),semanticSinkKey:'Out:event(uint256,uint256):1'};assert.equal(findings([first,second]).findings.length,2);});
