import type { Finding, ScanReport, Severity } from './types.js';

const labels: Record<Severity, string> = {
  critical: 'CRITICAL',
  high: 'HIGH',
  medium: 'MEDIUM',
  low: 'LOW',
};

function formatFinding(item: Finding): string {
  return [
    `${labels[item.severity]} ${item.ruleId} — ${item.title}`,
    `${item.file}:${item.startLine}`,
    item.description,
    `Impact: ${item.impact}`,
    `Evidence: ${item.evidence}`,
    `Fix: ${item.remediation}`,
    `Suggested policy: ${item.suggestedPolicy}`,
  ].join('\n');
}

export function formatTextReport(report: ScanReport): string {
  const header = [
    `VeilForge privacy readiness: ${report.score}/100 (${report.grade})`,
    `Findings: ${report.summary.critical} critical, ${report.summary.high} high, ${report.summary.medium} medium, ${report.summary.low} low`,
    `Sensitive selectors: ${report.exposure.sensitiveSelectors}`,
    `Externally callable functions: ${report.exposure.externallyCallableFunctions}`,
    `Source hash: ${report.sourceHash}`,
    `Report hash: ${report.reportHash}`,
  ].join('\n');

  const findings = report.findings.length
    ? report.findings.map(formatFinding).join('\n\n')
    : 'No findings detected by the current deterministic rule set.';

  const policies = report.policies.length
    ? report.policies
        .map((policy) => `${policy.recommendation.padEnd(10)} ${policy.signature} — ${policy.reason}`)
        .join('\n')
    : 'No externally callable functions detected.';

  return `${header}\n\n${findings}\n\nPolicy recommendations\n${policies}\n\n${report.disclaimer}`;
}

function escapeTable(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', '<br>');
}

export function formatMarkdownReport(report: ScanReport, projectName = 'VeilForge scan'): string {
  const findings = report.findings.length
    ? report.findings
        .map(
          (item) => `## ${item.ruleId} — ${item.title}\n\n` +
            `- **Severity:** ${labels[item.severity]}\n` +
            `- **Category:** ${item.category}\n` +
            `- **Location:** \`${item.file}:${item.startLine}-${item.endLine}\`\n` +
            `- **Confidence:** ${item.confidence}\n` +
            `- **Suggested APS policy:** ${item.suggestedPolicy}\n\n` +
            `### Why it matters\n\n${item.impact}\n\n` +
            `### Evidence\n\n\`\`\`solidity\n${item.evidence}\n\`\`\`\n\n` +
            `### Recommended remediation\n\n${item.remediation}\n\n` +
            (item.saferPattern
              ? `### Safer pattern\n\n\`\`\`solidity\n${item.saferPattern}\n\`\`\`\n`
              : ''),
        )
        .join('\n---\n\n')
    : 'No deterministic rule matched. Continue manual review; this is not a formal security audit.';

  const policyRows = report.policies.length
    ? report.policies
        .map(
          (policy) =>
            `| \`${escapeTable(policy.signature)}\` | ${policy.recommendation} | ${escapeTable(policy.reason)} |`,
        )
        .join('\n')
    : '| — | — | No externally callable functions detected. |';

  return `# ${projectName} — VeilForge Privacy Readiness Report\n\n` +
    `> Generated by VeilForge v${report.scannerVersion}. ${report.disclaimer}\n\n` +
    `## Executive summary\n\n` +
    `| Metric | Value |\n|---|---:|\n` +
    `| Privacy readiness | **${report.score}/100 (${report.grade})** |\n` +
    `| Critical findings | ${report.summary.critical} |\n` +
    `| High findings | ${report.summary.high} |\n` +
    `| Sensitive selectors | ${report.exposure.sensitiveSelectors} |\n` +
    `| Public state variables | ${report.exposure.publicStateVariables} |\n` +
    `| Public mappings | ${report.exposure.publicMappings} |\n` +
    `| Cross-contract findings | ${report.exposure.crossContractFindings} |\n\n` +
    `- **Source hash:** \`${report.sourceHash}\`\n` +
    `- **Report hash:** \`${report.reportHash}\`\n\n` +
    `## Prioritized findings\n\n${findings}\n\n` +
    `## APS-aligned selector recommendations\n\n` +
    `| Selector | Policy | Reason |\n|---|---|---|\n${policyRows}\n`;
}
