export const EXIT_CODES = Object.freeze({
  COMPLETED: 0, GENERIC: 1, ARGUMENT: 2, SOURCE: 3, SCAN_FAILED: 4,
  INCOMPLETE: 5, TIMEOUT: 6, ABORTED: 7, REPORT_INVALID: 8,
  EXPORT_INVALID: 9, OUTPUT: 10, PROTOCOL: 11, GATE_FAILED: 12, BENCHMARK_CONDITIONAL: 13, BENCHMARK_REGRESSION: 14,
});
